## Mappa - By OcZi
general:
  ## Frequency of spawn particles (in ticks).
  ## If you want to calculate with seconds convert it with:
  ## https://mapmaking.fr/tick/
  particle-frequency: 15

  ## Maximum visualizations that a player can see.
  player-max-visuals: 10

load:
  ## Resume sessions with warning tag due to some previous problem with them.
  resume-dangerous-sessions: true

  ## Resume all previous sessions at load.
  resume-all-sessions: false

  ## Map file sources to define the map file of a specific Map scheme.
  ## Useful to load/save sessions directly in the mini-game plugin file.
  ## Uncomment these lines if you want to use them
  ## map-source:
    ## MABedwars: "../MABedWars/maps.yml"

unload:
  ## Save all the sessions that are ready to be
  save-ready-sessions: true

file:
  save-format: "map-{id}"