## Mappa - By OcZi

in-game:
  ## Clear the tool value after set a property.
  ## Useful to not have a confusion and set another property with the same value.
  clear-tool-after-use: true

  ## Consider if precision vector tool falls on the floor of a block
  ## the entire block Y location is taken
  block-top-equals-block-location: true

load:
  ## Resume sessions with warning tag due to some previous problem with them.
  resume-dangerous-sessions: true

  ## Resume all previous sessions at load.
  resume-all-sessions: false

  ## Map file sources to define the map file of a specific Map scheme.
  ## Useful to load/save sessions directly in the mini-game plugin file.
  ## Uncomment these lines if you want to use them
  ## map-source:
    ## MABedwars: "../MABedwars/maps.yml"

unload:
  ## Save all the sessions that are ready to be
  save-ready-sessions: true

file:
  save-format: "map-{id}"